site:
  name: Programando
  url: https://programando.online
  max_items: 7
folders:
  pages: './app/pages'
  posts: './app/posts'
output:
  dir: './dist/' 
social:
  github: 'https://github.com/luizfnunes'
  youtube: 'https://www.youtube.com/@fernando.programador'
  twitter: 'https://twitter.com/fernando_progrm'